from telebot import types

class Keyboard():
	main_key = types.InlineKeyboardButton(text='Главное меню', callback_data='main_menu')

	keyboard_force_main = types.InlineKeyboardMarkup()
	keyboard_force_main.add(main_key)

	keyboard_start = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Начать', callback_data='await_start')
	keyboard_start.add(key)

	keyboard_main = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Старость', callback_data='oldness')
	keyboard_main.add(key)
	key = types.InlineKeyboardButton(text='Пострейв', callback_data='postrave')
	keyboard_main.add(key)
	key = types.InlineKeyboardButton(text='Кокон', callback_data='cocoon')
	keyboard_main.add(key)
	key = types.InlineKeyboardButton(text='Пустота', callback_data='emptiness')
	keyboard_main.add(key)
	key = types.InlineKeyboardButton(text='Расследование', callback_data='investigation')
	keyboard_main.add(key)
	key = types.InlineKeyboardButton(text='Между', callback_data='between')
	keyboard_main.add(key)
	key = types.InlineKeyboardButton(text='Анонимный чат', url='https://t.me/joinchat/REYAVc2UgIliNGU6')
	keyboard_main.add(key)
	key = types.InlineKeyboardButton(text='Новое пространство', callback_data='new_space')
	keyboard_main.add(key)
	key = types.InlineKeyboardButton(text='Задать вопрос', callback_data='question')
	keyboard_main.add(key)
	key = types.InlineKeyboardButton(text='Маршрут по пространству', callback_data='track')
	keyboard_main.add(key)

	keyboard_track = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Создать маршрут', callback_data='track_create')
	keyboard_track.add(key)
	key = types.InlineKeyboardButton(text='Пройти случайный маршрут', callback_data='track_follow_random')
	keyboard_track.add(key)
	key = types.InlineKeyboardButton(text='Маршрут 17 и более идентичностей _', callback_data='track_follow_main')
	keyboard_track.add(key)
	keyboard_track.add(main_key)

	keyboard_follow_track = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Следующий шаг', callback_data='track_next_step')
	keyboard_follow_track.add(key)
	keyboard_follow_track.add(main_key)

	keyboard_create_track = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Сохранить', callback_data='track_save')
	keyboard_create_track.add(key)
	keyboard_create_track.add(main_key)

	keyboard_emptiness = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Наполнить пространство', callback_data='fullfill_space')
	keyboard_emptiness.add(key)
	key = types.InlineKeyboardButton(text='Оставить пустоту', callback_data='main_menu')
	keyboard_emptiness.add(key)

	keyboard_fullfill = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Добавить в пространство', callback_data='fullfill_space')
	keyboard_fullfill.add(key)
	key = types.InlineKeyboardButton(text='Оставить пустоту', callback_data='main_menu')
	keyboard_fullfill.add(key)

	keyboard_between = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='слушать', url='https://audio-app-web.web.app/#/')
	keyboard_between.add(key)
	key = types.InlineKeyboardButton(text='Завершить пространство', callback_data='show_image_and_quit')
	keyboard_between.add(key)

	keyboard_investigation = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Отправить зацепку', callback_data='send_clue')
	keyboard_investigation.add(key)
	key = types.InlineKeyboardButton(text='На корм животным', url='https://www.donationalerts.com/r/canofworms')
	keyboard_investigation.add(key)
	key = types.InlineKeyboardButton(text='Завершить пространство', callback_data='show_image_and_quit')
	keyboard_investigation.add(key)

	keyboard_clue = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='На корм животным', url='https://www.donationalerts.com/r/canofworms')
	keyboard_clue.add(key)
	key = types.InlineKeyboardButton(text='Завершить пространство', callback_data='show_image_and_quit')
	keyboard_clue.add(key)

	keyboard_cocoon = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='кокон свободен', callback_data='cocoon_free')
	keyboard_cocoon.add(key)
	key = types.InlineKeyboardButton(text='кокон занят', callback_data='cocoon_occupied')
	keyboard_cocoon.add(key)
	keyboard_cocoon.add(main_key)

	keyboard_cocoon_occupied = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Прочитать про Кокон', callback_data='cocoon_about')
	keyboard_cocoon_occupied.add(key)
	keyboard_cocoon_occupied.add(main_key)

	keyboard_cocoon_free = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Начать общение', callback_data='cocoon_start')
	keyboard_cocoon_free.add(key)
	keyboard_cocoon_free.add(main_key)

	keyboard_new_space = types.InlineKeyboardMarkup()
	key = types.InlineKeyboardButton(text='Чат', url='https://t.me/joinchat/REYAVc2UgIliNGU6')
	keyboard_new_space.add(key)
	keyboard_new_space.add(main_key)